### ISSUE TITLE
LAB 36. incorrect URL for helm charts

### ISSUE THREAD

**Issue by mzikmund** [rancher/academy#12]
Links to stable and incubator has changed. The old ones through error 403

https://academy.rancher.com/assets/courseware/v1/c676ae18254bdfef1afb4d429c158c31/asset-v1:RANCHER+K101+2019+type@asset+block/Lab-36-Add-Custom-Catalogs.pdf

Name | Old Location | New Location
-- | -- | --
stable | https://kubernetes-charts.storage.googleapis.com | https://charts.helm.sh/stable
incubator | https://kubernetes-charts-incubator.storage.googleapis.com | https://charts.helm.sh/incubator

**Comment by oskapt** [comment]
- updated URLs
- did not update images
- uploaded to academy backend
